[WIP] better documentations
data-8/nbinteract pull request #36
Opened 2017-04-08 22:42 UTC by tonyyanga

2017-04-16 03:27 UTC, SaladRaider requested changes

2017-04-16 03:27 UTC, SaladRaider commented on README.md
> +4. Git remote domain whitelist, restricting which domain can the git repo be at. By default, only Githubis allowed. This can be overriden by setting `ALLOWED_WEB_DOMAINS` variable.
I think there is a space missing between 'Github' and 'is'

2017-04-18 19:24 UTC, SaladRaider commented
@tonyyanga I made some comments above. I think we can get this merged in very soon.

2017-04-18 22:06 UTC, tonyyanga commented
@SaladRaider problem solved.

2017-04-18 22:07 UTC, SaladRaider approved these changes

2017-04-18 22:07 UTC, merged